### ISSUE TITLE
Distance Sensor is always transmitting once object is created 

### ISSUE THREAD

**Issue by topshed** [RaspberryPiFoundation/python-build-hat#87]
As soon as a DistanceSensor object is created, the device starts transmitting ultrasonic pulses, even when not being asked for a distance measurement.  Even when the program is ended, transmission continues (until the device is unplugged).

**Comment by chrisruk** [comment]
I've just been testing this now I've got a soundcard that can capture ultrasound. Now if you do:

```
d = DistanceSensor('C')
del d
```

The deletion of the distance sensor will stop ultrasound being produced.  Or if you close the python REPL, that will also stop it.

It looks like the ultrasound sensor starts producing ultrasound when we do:

```
pwm 
set -1
```

Which is done when you create the DistanceSensor.  I think it might be a good idea to remain doing this, otherwise we would have to turn the sensor on / off, when using callbacks / requesting the distance.  I could look into doing that though, if the ultrasound interferes with something?

# Some FFTs:

![on](https://user-images.githubusercontent.com/19668907/168584634-7853b978-684a-4909-b57d-7c228f0f5ef0.png)

![off](https://user-images.githubusercontent.com/19668907/168584685-de1d0243-8582-4828-8014-cea18c5db9dd.png)

**Comment by chrisruk** [comment]
Closing for now, I think the 'del' change hopefully goes someway to addressing this issue.  Please re-open if we need more changes for this issue.
